########## 开发环境 ##########

spring:
  profiles:
    include: mybatis, redis, mail
  ### 数据源
  ### 该数据源配置并不影响Druid
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    # useUnicode=true&characterEncoding=UTF-8 : 编码格式
    # useUnicode : 是否使用Unicode字符集，如果参数characterEncoding设置为UTF-8或GBK，本参数值必须设置为true（省缺false）
    # characterEncoding : 当useUnicode设置为true时，指定字符编码。比如可设置为UTF-8或GBK
    # serverTimezone=GMT%2B8 : 设置时区为北京时区（东八区，“GMT”代表世界标准时间，“%2B”代表“+”）
    url: jdbc:mysql://127.0.0.1:3306/timor_blog?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: 123456
  
  data:
    # ElasticSearch
    elasticsearch:
      # ElasticSearch集群名称，省缺为“elasticsearch”
      cluster-name: timor-elasticsearch
      # 节点地址
      cluster-nodes: 127.0.0.1:9300
      properties:
        path:
        # 内嵌ElasticSearch实例。默认存储位置是工作目录的elastic目录
          home: target/elastic
        # 设置连接超时时间
        transport:
          tcp:
            connect_timeout: 120s

### log4j2
logging:
  config: classpath:config/dev/log4j2.xml
