########## 主配置文件
########## 参考：https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html

spring:
  profiles:
    active: dev
  http:
    # HTTP请求/响应字符编码设置
    encoding:
      enabled: true
      charset: UTF-8
      
  # jsp支持
  # 参考：https://blog.csdn.net/sky274548769/article/details/78742831
  # mvc:
  #   view:
  #     prefix: /WEB-INF/page/
  #     suffix: .jsp
  
  # thymeleaf模板引擎
  thymeleaf:
    encoding: UTF-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
  
  # 静态资源的访问配置
  # 参考：https://blog.csdn.net/plei_yue/article/details/79360645
  # resources:
    # static-locations: classpath:/static/

server:
  # 端口号
  port: 8888
  # 项目名
  servlet:
    context-path: 
