### MyBatis
mybatis:
  # 指向实体类的位置
  type-aliases-package: com.timor.entity
  # 指向mapper的xml文件位置
  mapper-locations: classpath:mybatis/mapper/*.xml
  # MyBatis配置文件位置
  config-location: classpath:mybatis/mybatis-config.xml
  
